# We will define input structure

# We will define ouput for each componenets
# 6 configuration have to be defined
'''
Data Injection --> Data Validation --> Data Transformation --> Model Trainer --> Model Evaluation --> Model Pusher
'''
# three dot means pass keyword

class DataIngestionArtifact:...
class DataValidationArtifact:...
class DataTransformationArtifact:...
class ModelTrainerArtifact:...
class ModelEvaluationArtifact:...
class ModelPusherArtifact:...
