# We will define input structure

# We will define ouput for each componenets
# 6 configuration have to be defined
'''
Data Injection --> Data Validation --> Data Transformation --> Model Trainer --> Model Evaluation --> Model Pusher
'''
# three dot means pass keyword

class DataIngestionConfig:...
class DataValidationConfig:...
class DataTransformationConfig:...
class ModelTrainerConfig:...
class ModelEvaluationConfig:...
class ModelPusherConfig:...
